controller:
  admin:
    username: admin
    password: admin123456

  serviceType: ClusterIP

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - credentials
    - ssh-credentials
    - plain-credentials

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  JCasC:
    defaultConfig: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "Jenkins final project CI/CD pipeline"

agent:
  enabled: true

serviceAccount:
  create: true
  name: jenkins

persistence:
  enabled: false
